view_mind_map_route:
    path:     /mind-map/
    defaults: { _controller: 'MindMapController::viewMindMapAction' }

select_note_route:
    path:     /select-note/
    defaults: { _controller: 'MindMapController::selectNoteAction' }

login_route:
    path:     /login/
    defaults: { _controller: 'AuthController::loginAction' }